### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [tent/http-link-go#1]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for http-link-go and versioning would help Debian keep up with development.

**Comment by titanous** [comment]
This code has not been touched in three years and it's unlikely that any meaningful changes will be merged. Also, as a general rule we don't do version numbers for our libraries.

**Comment by aviau** [comment]
For Deban its hard to keep up. I have to personally come and see if there is a new commit. However, we have scripts that checks for tags (Fedora also has this).

Just tagging a 1.0 release and creating a new tag when and if something new is merged will ensure that Debian packages depending on http-link-go are updated. This is relatively low efforts and will benefit distros.
